- hyperlink/_url.py
- hyperlink/test/common.py
- hyperlink/test/test_common.py
- hyperlink/test/test_scheme_registration.py
- hyperlink/test/test_url.py
- setup.py
- tox.ini
This PR covers hyperlink's method for handling of schemes without default support. 
As you may know, the URL scheme (e.g., http/ssh/mailto/etc.) controls some pretty important semantics for later parts of the URL. I've tried to make the list of built-in schemes as complete as possible, with ~60 schemes supported by default. 
That said, the list is always growing, and I didn't want to make the same mistake as the standard library's urlparse, by hardcoding several lists without some developer recourse.
Even though this PR only adds tests, I'd be very happy to get any feedback on the system as a whole.
> Integrating the scheme registration subsystem

- hyperlink/_url.py
- hyperlink/test/test_url.py
Per #16, hyperlink's inherited behavior was applying percent-decoding too broadly. Each percent-encodable field in the URL (userinfo, path, query string, and fragment), has certain special characters that should *never* be decoded [1].
To this end, this PR adds and utilizes a `_decode_XXX_part()` function for each of the fields, symmetrical to the `_encode_XXX_part()` that was already there.
Several test cases were added, as well as a general test for the invariant that multiple calls of `to_iri()` will not generate different URL objects.
@glyph has shown the most interest in this feature, so I've added him as reviewer.
[1]: To take the path as an example, the special characters include delimiters, such as the slash (`/`), question mark (`?`), and hash mark (`#`), as well as the percent …
> Fix percent decoding and normalization

- hyperlink/_url.py
Following up on my suggestion in #23. Makes this line a little more readable, and consistent with line 177:
```python
ret[c] = ret[v] = '%{0:02X}'.format(i)
```
Informal testing with `timeit` is inconclusive, suggesting they’re about the same time.
> Simplify the hex formatting in _url.py

- hyperlink/_url.py
- hyperlink/test/test_url.py
Pretty straightforward changes to require that `from_text` is only called with decoded strings (`unicode` objects on py2, etc.), per the discussion in #21 and #20.
> enforce decoding prior to calling from_text

- hyperlink/_url.py
- hyperlink/test/test_url.py
> *Defamiliarization or ostranenie (остранение) is the artistic technique of presenting to audiences common things in an unfamiliar or strange way in order to enhance perception of the familiar.*  -- (unrelated, but relevantly named)
OK, in a classic "this, but-not-this" sort of early review step, here is a sketch of URL without `family`, per #26. I think this is probably pretty close to what we want for that issue, but there's also probably feedback, particularly from @glyph, so let's have it :)
> Defamiliarization

- .travis.yml
- MANIFEST.in
- tox.ini
Adding a MANIFEST.in to include a few files (LICENSE, README, docs). Not sure if there's a python-hyper standard approach to this, so feedback is welcome!
> adding initial MANIFEST.in

- hyperlink/_url.py
- hyperlink/test/test_url.py
This PR makes URL.click work with URL objects, not just text, fixing #35.
There is one slightly outstanding issue, detailed in a `TODO` comment, which is that I need to remove the error message checks in Twisted's test suite. I haven't known anybody to depend on the byte-for-byte unchangingness of error messages as a public API, and in this case, it's restricting usability.
> URL.click() for URL objects

- TODO.md
- hyperlink/_url.py
- hyperlink/test/test_url.py
This PR adds a `normalize` method to `URL`, codifying five key normalization behaviors documented in RFC 3986:
* Decode unreserved characters (`RFC 3986 2.3`)                        
* Uppercase remaining percent-encoded octets (`RFC 3986 2.1`)          
* Convert scheme and host casing to lowercase (`RFC 3986 3.2.2`)       
* Resolve any "." and ".." references in the path (`RFC 3986 6.2.2`)   
* Ensure an ending slash on URLs with an empty path (`RFC 3986 6.2.3`) 
Which looks something like:
```python
>>> url = URL.from_text(u'Http://example.COM/a/../b/./c%2f?%61')         
>>> url.normalize().to_text()
u'http://example.com/b/c%2F?a'
```
This gives explicit control to users in a lot of gray areas where it wasn't clear whether we should be eager in enforcing these normal forms. Now, …
> Add URL.normalize()

- CHANGELOG.md
- docs/design.rst
- hyperlink/_url.py
- hyperlink/test/test_url.py
The URL constructor and the `.replace()` method now sensibly handle
dictionaries passed to the ‘query’ argument, instead of strictly
requiring it to be an iterable of `(key, value)` pairs (both of which
must be strings).
Examples:
```
URL(query={"foo": "bar"})
url.replace(query={"foo": "bar"})
```
This simplifies the API for the common use case, in which:
- the order of the items does not matter
(though Python >= 3.6 preserves dictionary order)
- no duplicate parameters are present
Updated the docs to include an example of this.
Fixes #50.
> Also accept dictionaries as ‘query=’ arguments

- docs/design.rst
The example showing Unicode support uses an incorrect French word.
As an alternative, use another phrase that is not only correct,
but also showcases the escaping of special characters,
in this example a single quote and an exclamation mark.
Oh, and it also rhymes. :)
> fix french example text in docs (excuse my french)

- TODO.md
- hyperlink/__init__.py
- hyperlink/_url.py
- hyperlink/test/test_decoded_url.py
- hyperlink/test/test_parse.py
This still needs some documentation, but to address #44 and the handful of issues surrounding the central problem, I present `DecodedURL`. It takes care of handling reserved characters so you don't have to. 
From the docstring:
> DecodedURL is a type meant to act as a higher-level interface to the URL. It is the unicode to URL's bytes. DecodedURL has almost exactly the same API as URL, but everything going in and out is in its maximally decoded state. All percent decoding is handled automatically.
> 
> Where applicable, a UTF-8 encoding is presumed. Be advised that some interactions, can raise UnicodeEncodeErrors and UnicodeDecodeErrors, just like when working with bytestrings.
> 
> Examples of such interactions include handling query strings encoding binary data, and paths containing …
> DecodedURL

- hyperlink/_url.py
- hyperlink/test/test_url.py
- requirements-test.txt
- setup.py
- tox.ini
As discussed in issue #19, Python's builtin idna support is outdated and broken. Thankfully the [idna](https://github.com/kjd/idna/) package exists. This PR switches to using that, instead of Python's builtin idna codec.
> Switch to using idna package

- hyperlink/_url.py
- hyperlink/test/test_decoded_url.py
Enhance `_percent_decode()` so that it properly decodes percents pairs even when non-ASCII is present, and extended docstring. Remove re-percent-encoding logic from DecodedURL. Now `_percent_decode()` actually does what the name says!
> Unicode mixed percent decoding

- hyperlink/_url.py
- hyperlink/test/test_url.py
Per #61. This PR adds a new argument to `_percent_decode()`, its variants, and `URL.normalize()`. 
This option (disabled by default, and enabled for normalize), exists to turn unmatched `%` characters to their encoded equivalent, correcting an otherwise improperly encoded URL. Major browsers don't do this by default, so it's currently limited to the explicit normalize step.
> Add encode_stray_percents functionality.

- README.md
- docs/index.rst
The examples were broken in several ways, probably due to changes in the library since they were first written:
* Replacing `scheme` from 'http' to 'https' seems to also require replacing `port` to match, otherwise it is maintained as port 80
* The `click` function on the github URL (without a trailing slash) takes one to `github.com/` rather than the org URL
* The URL referred to has moved, since the project was moved from `github.com/mahmoud` to `github.com/python-hyper` :)
* I also thought `str()` is more natural than `to_text()`
> Make first examples work

- hyperlink/_url.py
Fix this incorrect output when invalid host exception is raised
```
raise URLParseError('invalid host %r in url: %r')
hyperlink._url.URLParseError: invalid host %r in url: %r
```
> fix missing args in bad host exception

- .tox-coveragerc
- hyperlink/_url.py
- hyperlink/test/test_url.py
- tox.ini
Specifically, allow unescaped equal signs in query parameter values. Values are terminated by ampersands (`&`) or the fragment (`#`) or the end of the URL. See #38 for more details.
This change requires changing [Twisted's tests](https://github.com/twisted/twisted/blob/02a3221ed72e3385546f9421401bf40e360bb9bb/src/twisted/python/test/test_url.py#L484-L490), which inherited the overzealous escaping of urllib.
> Allow unescaped equal signs in query parameter values

- setup.py
This makes it easier to introspect licenses for installed packages (e.g. with [pip-licenses](https://pypi.org/project/pip-licenses/))
> Add PyPI license classifier

- src/hyperlink/_url.py
- src/hyperlink/test/test_url.py
> attempt at a fix for the rooted flag

- .travis.yml
There's currently no caching on the CI:
* https://travis-ci.org/python-hyper/hyperlink/jobs/622856289#L173
It's due to missing indentation in the config:
```yaml
cache:
directories:
- $HOME/.cache/pip
```
To fix it, indent:
```yaml
cache:
directories:
- $HOME/.cache/pip
```
Or, as only pip is being cached, there's a shortcut:
```yaml
cache: pip
```
* https://docs.travis-ci.com/user/caching/#pip-cache
Fixed cache:
https://travis-ci.org/hugovk/hyperlink/jobs/630664500#L177
---
Also, `sudo` is no longer needed: 	
* https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
> Fix Travis CI caching

- .gitignore
- MANIFEST.in
- pyproject.toml
- setup.py
- src/hyperlink/_socket.py
- src/hyperlink/_url.py
- src/hyperlink/test/common.py
- src/hyperlink/test/test_common.py
- src/hyperlink/test/test_decoded_url.py
- src/hyperlink/test/test_parse.py
- src/hyperlink/test/test_scheme_registration.py
- src/hyperlink/test/test_url.py
- tox.ini
This PR sets up the `black` linter.
The current branch does not actually run `black` in the default `tox` config, or in CI, so that the reviewer can see what changes are made *before* we reformat the code base.
To run `black`, use this command: `tox -e black`.  It will fail, since the code is not yet reformatted to comply with `black`'s conventions.
To test out the reformatting, run `tox -e black-reformat`.  At this point, running `black` (per above) should succeed.
Before merging, we need to (1) reformat the code, (2) add `black` to the default `tox` environment list (it's commented out for now) and (3) add the `black` `tox` environment to the CI config (4) remove `W504` from the `flake8` ignore list, as it won't be needed post-reformatting.
> Fade to black

- tox.ini
- Move some settings from `[default]` to `[testenv]`, since they are only used there.
- There is no need to prefix testing config with `test:` any more, since `[testenv]` only runs tests.
- Add comments, because yay comments.
> Clean up the Tox config a bit more

- src/hyperlink/_url.py
- tox.ini
This updates Sphinx to version 3 (from version 2).
One thing that is different is that Sphinx 3 will add type hint information to API documentation, for example:
```
hyperlink.parse(url: str, decoded: bool = True, lazy: bool = False) → Union[hyperlink._url.URL, hyperlink._url.DecodedURL]
```
This means that the manually added type information in the docstrings is no longer needed.
> Update to Sphinx3

- tox.ini
Try moving extra comment out of `rq.filter` line to make `requires.io` happy
> Cap coverage version for requires.io

- setup.py
Install the IDNA tables file.
On trying to switch Klein to [use the Hypothesis strategies now provided by Hyperlink](https://github.com/twisted/klein/pull/393), I got [build failures](https://travis-ci.org/github/twisted/klein/jobs/722089054#L575) due to the file being missing.
I though that `tox -e packaging` would notice this was missing, but it doesn't catch it.
> Install IDNA tables file.

- src/hyperlink/hypothesis.py
- src/hyperlink/test/common.py
- src/hyperlink/test/test_common.py
- tox.ini
Fix this failure on master:
```
black run-test: commands[0] | black --check setup.py src
would reformat /home/twm/dev/hyperlink/src/hyperlink/test/common.py
would reformat /home/twm/dev/hyperlink/src/hyperlink/test/test_common.py
would reformat /home/twm/dev/hyperlink/src/hyperlink/hypothesis.py
Oh no! 💥 💔 💥
3 files would be reformatted, 11 files would be left unchanged.
ERROR: InvocationError for command /home/twm/dev/hyperlink/.tox/black/bin/black --check setup.py src (exited with code 1)
```
> Reformat a few files with Black

- src/hyperlink/_url.py
- src/hyperlink/test/test_url.py
This demonstrates the failure afflicting https://github.com/twisted/treq/pull/304
> (Encoded)URL round-tripping of + in query

- src/hyperlink/_url.py
- src/hyperlink/test/test_decoded_url.py
- src/hyperlink/test/test_scheme_registration.py
Per the *interminable* discussion already present there, fixes #129.
> make hyperlink handle + like an HTML form post by default

- .appveyor.yml
These builds are not working any more and are blocking any other PR from passing CI.
> Remove Python 2.7 and Python 3.5 from the Windows build matrix.
